# Generated by Django 5.2.13 on 2026-04-20 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, default='Operations', max_length=60)),
                ('icon', models.CharField(blank=True, default='fact_check', max_length=80)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('billing', 'Billing'), ('residential', 'Residential'), ('system', 'System'), ('analytics', 'Analytics')], default='global', max_length=24)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist item',
                'verbose_name_plural': 'Checklist items',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('export', 'Export'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('balance', 'Balance'), ('note', 'Note'), ('status', 'Status'), ('system', 'System')], default='system', max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('actor', models.CharField(blank=True, default='System', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='main_app.apartment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='main_app.building')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='main_app.complex')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='main_app.owner')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='planned', max_length=24)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('action_label', models.CharField(blank=True, default='Open checklist', max_length=80)),
                ('icon', models.CharField(blank=True, default='fact_check', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='main_app.building')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='main_app.complex')),
            ],
            options={
                'verbose_name': 'Maintenance task',
                'verbose_name_plural': 'Maintenance tasks',
                'ordering': ['scheduled_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='PortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=20)),
                ('pinned', models.BooleanField(default=False)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_primary', models.CharField(blank=True, max_length=80)),
                ('action_secondary', models.CharField(blank=True, max_length=80)),
                ('action_state', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to='main_app.apartment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to='main_app.building')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to='main_app.complex')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_notifications', to='main_app.owner')),
            ],
            options={
                'verbose_name': 'Portal notification',
                'verbose_name_plural': 'Portal notifications',
                'ordering': ['-pinned', '-event_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('pressure', 'Pressure'), ('water', 'Water'), ('heating', 'Heating'), ('payment', 'Payment'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=24)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=24)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='main_app.apartment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='main_app.building')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='main_app.complex')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alerts', to='main_app.owner')),
            ],
            options={
                'verbose_name': 'System alert',
                'verbose_name_plural': 'System alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('status', models.CharField(choices=[('online', 'Online'), ('warning', 'Warning'), ('issue', 'Issue'), ('offline', 'Offline')], default='online', max_length=20)),
                ('icon', models.CharField(blank=True, default='apartment', max_length=80)),
                ('map_x', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('map_y', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('pressure_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flow_liters_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('uptime_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_nodes', to='main_app.building')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_nodes', to='main_app.complex')),
            ],
            options={
                'verbose_name': 'Telemetry node',
                'verbose_name_plural': 'Telemetry nodes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pressure_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flow_liters_day', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('uptime_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('issue_state', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='portal.telemetrynode')),
            ],
            options={
                'verbose_name': 'Telemetry sample',
                'verbose_name_plural': 'Telemetry samples',
                'ordering': ['-measured_at'],
            },
        ),
    ]
