# Generated by Django 5.2.13 on 2026-04-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(default='HydroFlow', max_length=120)),
                ('organization', models.CharField(default='HydroFlow Utility Management', max_length=180)),
                ('access_level', models.CharField(default='Full operations access', max_length=180)),
                ('role_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('timezone_name', models.CharField(default='Asia/Tashkent', max_length=80)),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('session_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=20)),
                ('note', models.CharField(default='Profile data is loaded from Django admin and the active backend session.', max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace profile',
                'verbose_name_plural': 'Workspace profiles',
            },
        ),
    ]
