# Generated by Django 5.2.13 on 2026-04-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_workspaceprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalStatusOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('residential', 'Residential'), ('transactions', 'Transactions'), ('maintenance', 'Maintenance')], max_length=24)),
                ('target_type', models.CharField(choices=[('complex', 'Complex'), ('building', 'Building'), ('apartment', 'Apartment'), ('transaction', 'Transaction'), ('maintenance', 'Maintenance')], max_length=24)),
                ('target_id', models.PositiveIntegerField()),
                ('status_value', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_status_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal status override',
                'verbose_name_plural': 'Portal status overrides',
                'ordering': ['-updated_at'],
                'unique_together': {('context', 'target_type', 'target_id')},
            },
        ),
    ]
