# Generated by Django 5.2.13 on 2026-05-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('cash', 'Cash'), ('manual', 'Manual'), ('charge', 'Charge')], max_length=20, verbose_name='Payment type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = incoming, negative = outgoing.', max_digits=14, verbose_name='Amount (UZS)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Balance before')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Balance after')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='External system ID (Payme/Click)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text='Administrator name or system.', max_length=255, verbose_name='Created by')),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional invoice linked to this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.invoice', verbose_name='Invoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main_app.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, unique=True)),
                ('account_id', models.CharField(max_length=255, verbose_name='Account (Owner ID)')),
                ('amount_tiyin', models.BigIntegerField(verbose_name='Amount (tiyin)')),
                ('state', models.IntegerField(default=0, verbose_name='State')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Raw payload from Payme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payme_data', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Payme transaction',
                'verbose_name_plural': 'Payme transactions',
            },
        ),
    ]
