# Generated by Django 6.0.4 on 2026-04-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('cash', 'Naqd pul'), ('manual', 'Qo\'lda kiritilgan'), ('charge', 'Hisobdan echish')], max_length=20, verbose_name='To\'lov turi')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Musbat = kirim, manfiy = chiqim', max_digits=14, verbose_name='Summa (so\'m)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='To\'lovdan oldingi balans')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='To\'lovdan keyingi balans')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Tashqi tizim ID (Payme/Click)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, help_text="Administrator ismi yoki 'system'", max_length=255, verbose_name='Kim tomonidan')),
                ('invoice', models.ForeignKey(blank=True, help_text='Agar bu to\'lov konkret invoice uchun bo\'lsa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.invoice', verbose_name='Hisob-faktura')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main_app.owner', verbose_name='Ega')),
            ],
            options={
                'verbose_name': 'To\'lov tranzaksiya',
                'verbose_name_plural': 'To\'lov tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payme_id', models.CharField(max_length=255, unique=True)),
                ('account_id', models.CharField(max_length=255, verbose_name='Account (Owner ID)')),
                ('amount_tiyin', models.BigIntegerField(verbose_name='Summa (tiyin)')),
                ('state', models.IntegerField(default=0, verbose_name='Holat')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Payme dan kelgan xom ma\'lumot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payme_data', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiya',
                'verbose_name_plural': 'Payme tranzaksiyalari',
            },
        ),
    ]
