# Generated by Django 5.2.13 on 2026-05-09 10:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Dekabr 2025', max_length=100, verbose_name='Davr nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='draft', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('buildings', models.ManyToManyField(blank=True, related_name='billing_periods', to='properties.building', verbose_name='Uylar')),
            ],
            options={
                'verbose_name': 'Xisoblash davri',
                'verbose_name_plural': 'Xisoblash davrlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BuildingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20)),
                ('gas_start', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gas_end', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('tariff', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('is_calculated', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_services', to='properties.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='billing.billingperiod')),
            ],
            options={
                'ordering': ['period__start_date', 'building__complex__title', 'building__number', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tariff', models.DecimalField(decimal_places=4, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=16)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties.apartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties.owner')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.billingperiod')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['-created_at', 'owner_id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20, verbose_name='Xizmat turi')),
                ('name', models.CharField(help_text='Masalan: Qozonxona xizmati, Gaz sarfi...', max_length=255, verbose_name='Xarajat nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Summa (so'm)")),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.building', verbose_name='Uy')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='billing.billingperiod', verbose_name='Davr')),
                ('section', models.ForeignKey(blank=True, help_text="Agar uyda seksiyalar bo'lsa (masalan 66-uy: A1, A5)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.buildingsection', verbose_name='Seksiya')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
        migrations.CreateModel(
            name='GasMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], help_text='Isitish uchun yoki GVS uchun gazh', max_length=20, verbose_name='Xizmat turi')),
                ('start_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Boshlang'ich ko'rsatkich (kub)")),
                ('end_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Oxirgi ko'rsatkich (kub)")),
                ('price_per_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="1 kub narxi (so'm)")),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_meter_readings', to='properties.building', verbose_name='Uy')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_meter_readings', to='billing.billingperiod', verbose_name='Davr')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_meter_readings', to='properties.buildingsection', verbose_name='Seksiya')),
            ],
            options={
                'verbose_name': "Gaz hisoblagich ko'rsatkichi",
                'verbose_name_plural': "Gaz hisoblagich ko'rsatkichlari",
            },
        ),
        migrations.CreateModel(
            name='HeatingApartmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_provided', models.PositiveIntegerField(blank=True, null=True)),
                ('heated_area', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_usages', to='properties.apartment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_usages', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['apartment__building__complex__title', 'apartment__building__number', 'apartment__number'],
            },
        ),
        migrations.CreateModel(
            name='HeatingCalculationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Umumiy xarajatlar (so'm)")),
                ('total_heated_area', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Umumiy qizdirilgan maydon (m²·kun)')),
                ('cost_per_sqm', models.DecimalField(decimal_places=4, max_digits=12, verbose_name="1 m²·kun narxi (so'm)")),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_summaries', to='properties.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_summaries', to='billing.billingperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heating_summaries', to='properties.buildingsection')),
            ],
            options={
                'verbose_name': 'Isitish hisoblash xulosasi',
                'verbose_name_plural': 'Isitish hisoblash xulosalari',
            },
        ),
        migrations.CreateModel(
            name='HeatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_dates', models.JSONField(default=list, help_text='Masalan: ["2025-12-10", "2025-12-25"]', verbose_name='Qizdirilmagan kunlar')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_records', to='properties.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_records', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Isitish hisobi',
                'verbose_name_plural': 'Isitish hisoblari',
            },
        ),
        migrations.CreateModel(
            name='HotWaterCalculationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=16, verbose_name="Umumiy xarajatlar (so'm)")),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy GVS sarfi (kub)')),
                ('tariff_per_m3', models.DecimalField(decimal_places=4, max_digits=12, verbose_name="1 kub tarifi (so'm)")),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_summaries', to='properties.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_summaries', to='billing.billingperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_water_summaries', to='properties.buildingsection')),
            ],
            options={
                'verbose_name': 'GVS hisoblash xulosasi',
                'verbose_name_plural': 'GVS hisoblash xulosalari',
            },
        ),
        migrations.CreateModel(
            name='HotWaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reading', models.DecimalField(blank=True, decimal_places=2, help_text="Davr boshidagi hisoblagich ko'rsatkichi", max_digits=10, null=True, verbose_name="Boshlang'ich ko'rsatkich (kub)")),
                ('end_reading', models.DecimalField(blank=True, decimal_places=2, help_text="Davr oxiridagi hisoblagich ko'rsatkichi", max_digits=10, null=True, verbose_name="Oxirgi ko'rsatkich (kub)")),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='properties.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': "GVS hisoblagich ko'rsatkichi",
                'verbose_name_plural': "GVS hisoblagich ko'rsatkichlari",
            },
        ),
        migrations.CreateModel(
            name='HotWaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('end_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_hot_water_readings', to='properties.apartment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['apartment__building__complex__title', 'apartment__building__number', 'apartment__number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_snapshot', models.CharField(help_text="Hisob yuborilgan paytdagi ega FIO — owner o'zgarsa ham saqlanadi", max_length=255, verbose_name='Ega (vaqt kesimi)')),
                ('heated_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Qizdirilgan maydon (m²·kun)')),
                ('heating_cost_per_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='1 m² uchun narx (isitish)')),
                ('heating_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Isitish summasi (so'm)")),
                ('hot_water_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GVS sarfi (kub)')),
                ('hot_water_tariff', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name="GVS tarifi (so'm/kub)")),
                ('hot_water_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="GVS summasi (so'm)")),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Jami summa (so'm)")),
                ('is_recalculated', models.BooleanField(default=False, verbose_name='Qayta hisoblanganmih')),
                ('recalculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Qayta hisoblash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('payme', 'Payme'), ('click', 'Click'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='properties.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalculation_logs', to='billing.billingperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='buildingservice',
            constraint=models.UniqueConstraint(fields=('period', 'building', 'service_type'), name='uniq_building_service_period_type'),
        ),
        migrations.AddConstraint(
            model_name='heatingapartmentusage',
            constraint=models.UniqueConstraint(fields=('service', 'apartment'), name='uniq_heating_usage_service_apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='heatingrecord',
            unique_together={('period', 'apartment')},
        ),
        migrations.AlterUniqueTogether(
            name='hotwatermeterreading',
            unique_together={('period', 'apartment')},
        ),
        migrations.AddConstraint(
            model_name='hotwaterreading',
            constraint=models.UniqueConstraint(fields=('service', 'apartment'), name='uniq_hot_water_reading_service_apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('period', 'apartment')},
        ),
    ]
