# Generated by Django 6.0.4 on 2026-04-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Dekabr 2025', max_length=100, verbose_name='Davr nomi')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopiq')], default='open', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('buildings', models.ManyToManyField(related_name='billing_periods', to='main_app.building', verbose_name='Uylar')),
            ],
            options={
                'verbose_name': 'Xisoblash davri',
                'verbose_name_plural': 'Xisoblash davrlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Isitish'), ('hot_water', 'Issiq suv')], max_length=20, verbose_name='Xizmat turi')),
                ('name', models.CharField(help_text='Masalan: Qozonxona xizmati, Gaz sarfi...', max_length=255, verbose_name='Xarajat nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Summa (so\'m)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='main_app.building', verbose_name='Uy')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='billing.billingperiod', verbose_name='Davr')),
                ('section', models.ForeignKey(blank=True, help_text='Agar uyda seksiyalar bo\'lsa (masalan 66-uy: A1, A5)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='main_app.buildingsection', verbose_name='Seksiya')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
        migrations.CreateModel(
            name='GasMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Isitish'), ('hot_water', 'Issiq suv')], help_text='Isitish uchun yoki GVS uchun gazh', max_length=20, verbose_name='Xizmat turi')),
                ('start_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Boshlang\'ich ko\'rsatkich (kub)')),
                ('end_reading', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oxirgi ko\'rsatkich (kub)')),
                ('price_per_m3', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1 kub narxi (so\'m)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_meter_readings', to='main_app.building', verbose_name='Uy')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_meter_readings', to='billing.billingperiod', verbose_name='Davr')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_meter_readings', to='main_app.buildingsection', verbose_name='Seksiya')),
            ],
            options={
                'verbose_name': 'Gaz hisoblagich ko\'rsatkichi',
                'verbose_name_plural': 'Gaz hisoblagich ko\'rsatkichlari',
            },
        ),
        migrations.CreateModel(
            name='HeatingCalculationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Umumiy xarajatlar (so\'m)')),
                ('total_heated_area', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Umumiy qizdirilgan maydon (m²·kun)')),
                ('cost_per_sqm', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='1 m²·kun narxi (so\'m)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_summaries', to='main_app.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_summaries', to='billing.billingperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heating_summaries', to='main_app.buildingsection')),
            ],
            options={
                'verbose_name': 'Isitish hisoblash xulosasi',
                'verbose_name_plural': 'Isitish hisoblash xulosalari',
            },
        ),
        migrations.CreateModel(
            name='HotWaterCalculationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Umumiy xarajatlar (so\'m)')),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy GVS sarfi (kub)')),
                ('tariff_per_m3', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='1 kub tarifi (so\'m)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_summaries', to='main_app.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_summaries', to='billing.billingperiod')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_water_summaries', to='main_app.buildingsection')),
            ],
            options={
                'verbose_name': 'GVS hisoblash xulosasi',
                'verbose_name_plural': 'GVS hisoblash xulosalari',
            },
        ),
        migrations.CreateModel(
            name='HeatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_dates', models.JSONField(default=list, help_text='Masalan: ["2025-12-10", "2025-12-25"]', verbose_name='Qizdirilmagan kunlar')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_records', to='main_app.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_records', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Isitish hisobi',
                'verbose_name_plural': 'Isitish hisoblari',
                'unique_together': {('period', 'apartment')},
            },
        ),
        migrations.CreateModel(
            name='HotWaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Davr boshidagi hisoblagich ko\'rsatkichi', max_digits=10, null=True, verbose_name='Boshlang\'ich ko\'rsatkich (kub)')),
                ('end_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Davr oxiridagi hisoblagich ko\'rsatkichi', max_digits=10, null=True, verbose_name='Oxirgi ko\'rsatkich (kub)')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='main_app.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'GVS hisoblagich ko\'rsatkichi',
                'verbose_name_plural': 'GVS hisoblagich ko\'rsatkichlari',
                'unique_together': {('period', 'apartment')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_snapshot', models.CharField(help_text='Hisob yuborilgan paytdagi ega FIO — owner o\'zgarsa ham saqlanadi', max_length=255, verbose_name='Ega (vaqt kesimi)')),
                ('heated_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Qizdirilgan maydon (m²·kun)')),
                ('heating_cost_per_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='1 m² uchun narx (isitish)')),
                ('heating_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Isitish summasi (so\'m)')),
                ('hot_water_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GVS sarfi (kub)')),
                ('hot_water_tariff', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='GVS tarifi (so\'m/kub)')),
                ('hot_water_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='GVS summasi (so\'m)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa (so\'m)')),
                ('is_recalculated', models.BooleanField(default=False, verbose_name='Qayta hisoblanganmih')),
                ('recalculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Qayta hisoblash vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='main_app.apartment', verbose_name='Kvartira')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.billingperiod', verbose_name='Davr')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
                'unique_together': {('period', 'apartment')},
            },
        ),
    ]
