# Generated by Django 5.2.13 on 2026-04-22 19:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingperiod',
            name='buildings',
            field=models.ManyToManyField(blank=True, related_name='billing_periods', to='properties.building', verbose_name='Uylar'),
        ),
        migrations.AlterField(
            model_name='billingperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.building', verbose_name='Uy'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Agar uyda seksiyalar bo'lsa (masalan 66-uy: A1, A5)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.buildingsection', verbose_name='Seksiya'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='service_type',
            field=models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20, verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='gasmeterreading',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_meter_readings', to='properties.building', verbose_name='Uy'),
        ),
        migrations.AlterField(
            model_name='gasmeterreading',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_meter_readings', to='properties.buildingsection', verbose_name='Seksiya'),
        ),
        migrations.AlterField(
            model_name='gasmeterreading',
            name='service_type',
            field=models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], help_text='Isitish uchun yoki GVS uchun gazh', max_length=20, verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='heatingcalculationsummary',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_summaries', to='properties.building'),
        ),
        migrations.AlterField(
            model_name='heatingcalculationsummary',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heating_summaries', to='properties.buildingsection'),
        ),
        migrations.AlterField(
            model_name='heatingrecord',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_records', to='properties.apartment', verbose_name='Kvartira'),
        ),
        migrations.AlterField(
            model_name='hotwatercalculationsummary',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_summaries', to='properties.building'),
        ),
        migrations.AlterField(
            model_name='hotwatercalculationsummary',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hot_water_summaries', to='properties.buildingsection'),
        ),
        migrations.AlterField(
            model_name='hotwatermeterreading',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='properties.apartment', verbose_name='Kvartira'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.apartment', verbose_name='Kvartira'),
        ),
        migrations.CreateModel(
            name='BuildingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20)),
                ('gas_start', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gas_end', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('tariff', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('is_calculated', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_services', to='properties.building')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='billing.billingperiod')),
            ],
            options={
                'ordering': ['period__start_date', 'building__complex__title', 'building__number', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('heating', 'Heating'), ('hot_water', 'Hot water')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tariff', models.DecimalField(decimal_places=4, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=16)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties.apartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='properties.owner')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.billingperiod')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['-created_at', 'owner_id'],
            },
        ),
        migrations.CreateModel(
            name='HeatingApartmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_provided', models.PositiveIntegerField(blank=True, null=True)),
                ('heated_area', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_usages', to='properties.apartment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_usages', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['apartment__building__complex__title', 'apartment__building__number', 'apartment__number'],
            },
        ),
        migrations.CreateModel(
            name='HotWaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('end_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_hot_water_readings', to='properties.apartment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_water_readings', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['apartment__building__complex__title', 'apartment__building__number', 'apartment__number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('payme', 'Payme'), ('click', 'Click'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='properties.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalculation_logs', to='billing.billingperiod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='billing.buildingservice')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='buildingservice',
            constraint=models.UniqueConstraint(fields=('period', 'building', 'service_type'), name='uniq_building_service_period_type'),
        ),
        migrations.AddConstraint(
            model_name='heatingapartmentusage',
            constraint=models.UniqueConstraint(fields=('service', 'apartment'), name='uniq_heating_usage_service_apartment'),
        ),
        migrations.AddConstraint(
            model_name='hotwaterreading',
            constraint=models.UniqueConstraint(fields=('service', 'apartment'), name='uniq_hot_water_reading_service_apartment'),
        ),
    ]
