# Generated by Django 5.2.13 on 2026-05-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.apartment',),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.building',),
        ),
        migrations.CreateModel(
            name='BuildingSection',
            fields=[
            ],
            options={
                'verbose_name': 'Seksiya',
                'verbose_name_plural': 'Seksiyalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.buildingsection',),
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
            ],
            options={
                'verbose_name': 'Turar joy majmuasi',
                'verbose_name_plural': 'Turar joy majmualari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.complex',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.owner',),
        ),
    ]
