# Generated by Django 6.0.4 on 2026-04-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Uy raqami')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Uy',
                'verbose_name_plural': 'Uylar',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Turar joy majmuasi',
                'verbose_name_plural': 'Turar joy majmualari',
            },
        ),
        migrations.CreateModel(
            name='BuildingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Seksiya nomi')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main_app.building', verbose_name='Uy')),
            ],
            options={
                'verbose_name': 'Seksiya',
                'verbose_name_plural': 'Seksiyalar',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Kvartira raqami')),
                ('area', models.FloatField(verbose_name='Maydon (m²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255, verbose_name='Yaratuvchi')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='main_app.building', verbose_name='Uy')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='main_app.buildingsection', verbose_name='Seksiya')),
            ],
            options={
                'verbose_name': 'Kvartira',
                'verbose_name_plural': 'Kvartiralar',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main_app.complex', verbose_name='Turar joy majmuasi'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='FIO')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Balans (so\'m)')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_status', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main_app.apartment', verbose_name='Kvartira')),
            ],
            options={
                'verbose_name': 'Ega',
                'verbose_name_plural': 'Egalar',
            },
        ),
    ]
