# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="area",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Maydon (m²)"),
        ),
    ]
