# Generated by Django 5.2.13 on 2026-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_force_single_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AddField(
            model_name='owner',
            name='has_contract',
            field=models.BooleanField(default=False, verbose_name='Dogovor bor'),
        ),
    ]
